# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
set_param xicom.use_bs_reader 1
create_project -in_memory -part xc7a100tcsg324-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir {C:/Users/L03068681/Contacts/Desktop/Eqiupo1/intento final 2/Referencia LCD/PFV3RaulSebas/PFV3RaulSebas.cache/wt} [current_project]
set_property parent.project_path {C:/Users/L03068681/Contacts/Desktop/Eqiupo1/intento final 2/Referencia LCD/PFV3RaulSebas/PFV3RaulSebas.xpr} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language VHDL [current_project]
set_property ip_output_repo {c:/Users/L03068681/Contacts/Desktop/Eqiupo1/intento final 2/Referencia LCD/PFV3RaulSebas/PFV3RaulSebas.cache/ip} [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_vhdl -library xil_defaultlib {
  {C:/Users/L03068681/Contacts/Desktop/Eqiupo1/intento final 2/Referencia LCD/PFV3RaulSebas/PFV3RaulSebas.srcs/sources_1/new/BCDtoASCII.vhd}
  {C:/Users/L03068681/Contacts/Desktop/Eqiupo1/intento final 2/Referencia LCD/PFV3RaulSebas/PFV3RaulSebas.srcs/sources_1/new/BINARYtoBCD.vhd}
  {C:/Users/L03068681/Contacts/Desktop/Eqiupo1/intento final 2/Referencia LCD/PFV3RaulSebas/PFV3RaulSebas.srcs/sources_1/INTESC_LCD_8BITS_RevD/CARACTERES_ESPECIALES_REVD.vhd}
  C:/Users/L03068681/Contacts/Desktop/INTESC_LCD_8BITS_RevD/COMANDOS_LCD_REVD.vhd
  {C:/Users/L03068681/Contacts/Desktop/Eqiupo1/intento final 2/Referencia LCD/PFV3RaulSebas/PFV3RaulSebas.srcs/sources_1/INTESC_LCD_8BITS_RevD/PROCESADOR_LCD_REVD.vhd}
  {C:/Users/L03068681/Contacts/Desktop/Eqiupo1/intento final 2/Referencia LCD/PFV3RaulSebas/PFV3RaulSebas.srcs/sources_1/imports/PFV3_Raul_Sebas/TWICtl.vhdl}
  {C:/Users/L03068681/Contacts/Desktop/Eqiupo1/intento final 2/Referencia LCD/PFV3RaulSebas/PFV3RaulSebas.srcs/sources_1/imports/PFV3_Raul_Sebas/TempSensorCtl.vhdl}
  {C:/Users/L03068681/Contacts/Desktop/Eqiupo1/intento final 2/Referencia LCD/PFV3RaulSebas/PFV3RaulSebas.srcs/sources_1/imports/new/one_shot.vhd}
  {C:/Users/L03068681/Contacts/Desktop/Eqiupo1/intento final 2/Referencia LCD/PFV3RaulSebas/PFV3RaulSebas.srcs/sources_1/INTESC_LCD_8BITS_RevD/LIB_LCD_INTESC_REVD.vhd}
}
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc {{C:/Users/L03068681/Contacts/Desktop/Eqiupo1/intento final 2/Referencia LCD/PFV3RaulSebas/PFV3RaulSebas.srcs/constrs_1/imports/LCD/Nexys-4-DDR-Master.xdc}}
set_property used_in_implementation false [get_files {{C:/Users/L03068681/Contacts/Desktop/Eqiupo1/intento final 2/Referencia LCD/PFV3RaulSebas/PFV3RaulSebas.srcs/constrs_1/imports/LCD/Nexys-4-DDR-Master.xdc}}]

set_param ips.enableIPCacheLiteLoad 0
close [open __synthesis_is_running__ w]

synth_design -top LIB_LCD_INTESC_REVD -part xc7a100tcsg324-1


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef LIB_LCD_INTESC_REVD.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file LIB_LCD_INTESC_REVD_utilization_synth.rpt -pb LIB_LCD_INTESC_REVD_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
